<?php
$form = Mage::registry("message_form");
$headerText = "";
if($form) {
    $headerText = Mage::helper("ves_formbuilder")->__('Form "%s" - Messages Manager', $form->getTitle());
} else {
    $headerText = Mage::helper("ves_formbuilder")->__("Messages Manager");
}
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products"><?php echo $headerText; ?></h3></td>
        <td class="a-right">
            <?php echo $this->getButtonsHtml() ?>
            <!-- Start of Displaying of your custom import form -->
			<?php echo $this->getImportButtonHtml() ?>
			<!-- End of Displaying of your custom import form -->
        </td>
    </tr>
</table>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>