<?php
$form_data = $this->getData('form_data');
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$attribute_code = isset($field['attribute_code'])?$field['attribute_code']:'';
$other_property = isset($field['other_property'])?$field['other_property']:'';
$cid = $field['cid'];
$field_name = Ves_FormBuilder_Model_Form::FIELD_NAME_PREFIX.$cid;

$available_fields = Mage::helper('ves_formbuilder/fields')->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates = $field_validate;
$field_help = isset($options['description'])?$options['description']:'';
$field_class = isset($options['class'])?$options['class']:'';

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$list_options = array();
$selectedvalue = "";
if($attribute_code && $_product = Mage::registry('current_product')) {
	$product_id = $_product->getId();
	$product = Mage::getModel('catalog/product')->setStoreId(Mage::app()->getStore()->getId())->load($product_id);
	$selectedvalue  = $product->getAttributeText($attribute_code);
	$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product',$attribute_code);
   	$list_options = $attribute->getSource()->getAllOptions();
}

if($list_options){
	if(!isset($options['options']) || !is_array($options['options']) || !$options['options']){
		$options['options'] = array();
	}
	foreach($list_options as $key => $value){
		$tmp = array();
		$tmp['label'] = $value['label'];
		$tmp['checked'] = false;
		if($selectedvalue && in_array($selectedvalue, $value)){
			$tmp['checked'] = true;
		}
		$options['options'][] = $tmp;
	}
}
?>
<label for="<?php echo $field_name; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo (1==$required)?'<em>*</em>':'';?><?php echo $label; ?></label>
<div class="input-box">
	<?php
	if($options['options']) { ?>
	<select name="<?php echo $field_name; ?>" id="<?php echo $field_name; ?>" title="<?php echo $field_name; ?>" class="<?php echo $field_class; ?> <?php echo (1==$required)?'required-entry':''; ?> <?php echo $validates; ?>" <?php echo $other_property; ?>>
		<?php if(isset($options['include_blank_option']) && $options['include_blank_option']) { ?>
		<option value=""></option>
		<?php } ?>
		<?php foreach($options['options'] as $key=>$val) {
			$item_label = $val['label'];
			$item_checked = $val['checked'];
			if($form_data && isset($form_data[$field_name]) && $form_data[$field_name] == $item_label){
				$item_checked = true;
			}
			?>
			<option value="<?php echo Mage::helper('core')->quoteEscape($item_label); ?>" <?php echo ($item_checked)?'selected="selected"':''; ?>><?php echo $item_label; ?></option>
			<?php } ?>
		</select>
		<?php }
		?>
		<?php if($field_help) { ?>
		<span class="help-block"><?php echo $field_help ?></span>
		<?php } ?>
	</div>