<?php
$form_data = $this->getData('form_data');
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$default_email = "";
$use_customer_email = isset($field['use_customer_email'])?(int)$field['use_customer_email']:0;
$customer = Mage::getSingleton('customer/session')->getCustomer();
if($use_customer_email && $customer) {
	$default_email = $customer->getEmail();
}
if(!$default_email) {
	$default_email = isset($field['default_email'])?$field['default_email']:'';
}


$cid = $field['cid'];
$field_name = Ves_FormBuilder_Model_Form::FIELD_NAME_PREFIX.$cid;

$available_fields = Mage::helper('ves_formbuilder/fields')->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates = $field_validate;
$field_help = isset($options['description'])?$options['description']:'';
$field_class = isset($options['class'])?$options['class']:'';

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$size = isset($options['size'])?$options['size']:'';

?>
<div class="subtemplate-wrapper">
	<label for="<?php echo $field_name; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo (1==$required)?'<em>*</em>':'';?><?php echo $label; ?></label>
	<div class="row">
		<div class="<?php echo isset($field['fieldcol'])?'col-sm-'.$field['fieldcol']:'col-sm-12'; ?>">
			<div class="subtemplate-inner">
				<div class="input-box">
					<input name="<?php echo $field_name; ?>" id="<?php echo $field_name; ?>" title="<?php echo $label; ?>" value="<?php echo ($form_data && isset($form_data[$field_name]))?$form_data[$field_name]:$default_email; ?>" class="input-text <?php echo $field_class; ?> <?php echo (1==$required)?'required-entry':''; ?> <?php echo $validates; ?> <?php echo $size; ?>" type="text" />
					<?php if($field_help) { ?>
					<span class="help-block"><?php echo $field_help; ?></span>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>
