<?php
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$cid = $field['cid'];
$field_name = Ves_FormBuilder_Model_Form::FIELD_NAME_PREFIX.$cid;

$available_fields = Mage::helper('ves_formbuilder/fields')->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates = $field_validate;
$field_help = isset($options['description'])?$options['description']:'';
$field_class = isset($options['class'])?$options['class']:'';

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$image_type = isset($options['image_type'])?$options['image_type']:'png,jpg,gif,jpeg,zip,doc,pdf';
$image_maximum_size = isset($options['image_maximum_size'])?$options['image_maximum_size']:10;

?>
<label for="<?php echo $field_name; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo (1==$required)?'<em>*</em>':'';?><?php echo $label; ?></label>
<div class="input-box">
	<input name="form_file[<?php echo $cid ?>]" id="<?php echo $field_name; ?>" title="<?php echo $label; ?>" class="input-text <?php echo $field_class; ?> <?php echo (1==$required)?' required-entry':''; ?> <?php echo $validates; ?>" type="file" />
	<?php if($field_help) { ?>
	<span class="help-block"><?php echo $field_help; ?></span>
	<?php } ?>
</div>