<?php
$form_data = $this->getData('form_data');
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$cid = $field['cid'];
$attribute_code = isset($field['attribute_code'])?$field['attribute_code']:'';
$field_name = Ves_FormBuilder_Model_Form::FIELD_NAME_PREFIX.$cid;

$available_fields = Mage::helper('ves_formbuilder/fields')->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates = $field_validate;
$field_help = isset($options['description'])?$options['description']:'';
$field_class = isset($options['class'])?$options['class']:'';

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
$currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();
$size = isset($options['size'])?$options['size']:'';

$default_input = "";
if(!$default_input && $attribute_code && $_product = Mage::registry('current_product')) {
	$product_id = $_product->getId();
	$_resource = Mage::getSingleton('catalog/product')->getResource();
	$default_input = $_resource->getAttributeRawValue($product_id,  $attribute_code, Mage::app()->getStore());
}
?>
<label for="<?php echo $field_name; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo (1==$required)?'<em>*</em>':'';?><?php echo $label; ?></label>
<div class="input-box">

	<?php echo $currency_symbol; ?>
	<input name="<?php echo $field_name; ?>" id="<?php echo $field_name; ?>" title="<?php echo $label; ?>" value="<?php echo ($form_data && isset($form_data[$field_name]))?$form_data[$field_name]:$default_input; ?>" placeholder="00.00" class="input-text <?php echo $field_class; ?> <?php echo (1==$required)?'required-entry':''; ?> <?php echo $validates; ?> <?php echo $size; ?>" type="text" />
	<?php if($field_help) { ?>
	<span class="help-block"><?php echo $field_help ?></span>
	<?php } ?>

</div>