<?php
$form_data = $this->getData('form_data');
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$cid = $field['cid'];
$field_name = Ves_FormBuilder_Model_Form::FIELD_NAME_PREFIX.$cid;

$available_fields = Mage::helper('ves_formbuilder/fields')->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates = $field_validate;
$field_help = isset($options['description'])?$options['description']:'';
$field_class = isset($options['class'])?$options['class']:'';

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}

$limit = isset($field['limit'])?(int)$field['limit']:5;
$default = isset($field['default'])?(float)$field['default']:0;

?>
<label for="<?php echo $field_name; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo (1==$required)?'<em>*</em>':'';?><?php echo $label; ?></label>
<div class="input-box">
	<input name="<?php echo $field_name; ?>" id="<?php echo $field_name; ?>" title="<?php echo $label; ?>" value="<?php echo ($form_data && isset($form_data[$field_name]))?$form_data[$field_name]:''; ?>" class="input-text <?php echo (1==$required)?'required-entry':''; ?>" type="hidden"/>
	<input name="<?php echo $field_name."_limit"; ?>" id="<?php echo $field_name."_limit"; ?>" title="<?php echo $label; ?>" value="<?php echo $limit; ?>" class="input-text <?php echo $field_class; ?>" type="hidden"/>
	<div id="<?php echo $field_name."_rating"; ?>" class="ves-rating-play"></div>
	<script type="text/javascript">
		jQuery('#<?php echo $field_name."_rating"; ?>').raty({
			path: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."ves_formbuilder/rating/"; ?>',
			score: <?php echo $default; ?>,
			number: <?php echo $limit; ?>,
			targetScore: '#<?php echo $field_name; ?>',
		  	click: function(score, evt) {
		  		jQuery('#<?php echo $field_name; ?>').val(score);
		    	return false;
		  	}
		});
	</script>
	<?php if($field_help) { ?>
	<span class="help-block"><?php echo $field_help; ?></span>
	<?php } ?>
</div>