<?php
$form_data = $this->getData('form_data');
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$cid = $field['cid'];
$field_name = Ves_FormBuilder_Model_Form::FIELD_NAME_PREFIX.$cid;

$available_fields = Mage::helper('ves_formbuilder/fields')->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type])?$available_fields[$field_type]:'';
$validates = $field_validate;
$field_help = isset($options['description'])?$options['description']:'';
$field_class = isset($options['class'])?$options['class']:'';

if($field_validate && is_array($field_validate)) {
	$validates = implode(" ", $field_validate);
}
?>
<label for="<?php echo $field_name; ?>" class="<?php echo (1==$required)?'required':''; ?>"><?php echo (1==$required)?'<em>*</em>':'';?><?php echo $label; ?></label>
<div class="input-box">

	<input name="<?php echo $field_name; ?>" id="<?php echo $field_name; ?>" title="<?php echo $label; ?>" value="<?php echo ($form_data && isset($form_data[$field_name]))?$form_data[$field_name]:''; ?>" class="input-text <?php echo $field_class; ?> <?php echo (1==$required)?'required-entry':''; ?> <?php echo $validates; ?>" type="hidden"/>

	<div class="input-line">
		<span class="hours">
			<select name="<?php echo $field_name.'_hours'; ?>" id="<?php echo $field_name.'_hours'; ?>" class="<?php echo (1==$required)?'required-entry':''; ?> validate-zero-or-greater" onchange="buildTimeValue('<?php echo $field_name; ?>')">

				<?php
				for($i=0; $i<24; $i++) {
					$k = $i;
					if($i<10) {
						$k = '0'.$i;
					} ?>
					<option value="<?php echo $k; ?>"><?php echo $k; ?></option>
					<?php
				}
				?>

			</select>
			<label><?php echo $this->__("HH"); ?></label>
		</span>

		<span class="above-line">:</span>
		<span class="minutes">
			<select name="<?php echo $field_name.'_minutes'; ?>" id="<?php echo $field_name.'_minutes'; ?>" class="<?php echo (1==$required)?'required-entry':''; ?> validate-zero-or-greater" onchange="buildTimeValue('<?php echo $field_name; ?>')">

				<?php
				for($i=0; $i<60; $i++) {
					$k = $i;
					if($i<10) {
						$k = '0'.$i;
					} ?>
					<option value="<?php echo $k; ?>"><?php echo $k ?></option>
					<?php }
					?>

				</select>
				<label><?php echo $this->__("MM"); ?></label>
			</span>

			<span class="above-line">:</span>
			<span class="seconds">
				<select name="<?php echo $field_name.'_seconds'; ?>" id="<?php echo $field_name.'_seconds'; ?>" class="<?php echo (1==$required)?'required-entry':''; ?> validate-zero-or-greater" onchange="buildTimeValue('<?php echo $field_name; ?>')">

					<?php
					for($i=0; $i<60; $i++) {
						$k = $i;
						if($i<10) {
							$k = '0'.$i;
						} ?>
						<option value="<?php echo $k; ?>"><?php echo $k; ?></option>
						<?php }
						?>
					</select>
					<label><?php echo $this->__("SS"); ?></label>
				</span>

				<span class="am_pm">
					<select name="<?php echo $field_name.'_am_pm'; ?>" id="<?php echo $field_name.'_am_pm'; ?>" class="" onchange="buildTimeValue('<?php echo $field_name; ?>')">
						<option value="AM"><?php echo $this->__("AM"); ?></option>
						<option value="PM"><?php echo $this->__("PM"); ?></option>
					</select>
				</span>
			</div>

			<?php if($field_help) { ?>
			<span class="help-block"><?php echo $field_help; ?></span>
			<?php } ?>

		</div>